// <auto-generated />
namespace AprendendoEF.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Add_ForeignKey_GrupoProduto_In_Produto : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_ForeignKey_GrupoProduto_In_Produto));
        
        string IMigrationMetadata.Id
        {
            get { return "201704071747170_Add_ForeignKey_GrupoProduto_In_Produto"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
